name: Rust

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        env:
          MONGO_INITDB_DATABASE: test
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        - 27017:27017

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd preference-be/ && cargo build --verbose
    - name: Run tests
      run: cd preference-be/ && cargo test --verbose
